# File: .../sequence/operators/__init__.py
# Description: Central registration point for all sequence operators.

import bpy
from . import operator
from . import camera_operators
from . import io_operators

# A single tuple containing all operator classes to be registered

classes = (
    # from camera_operators.py
    camera_operators.ResetCameraSettings,
    camera_operators.Align4DCameraToView,
    camera_operators.Delete4DCamera,

    # from io_operators.py
    io_operators.ImportWorkScheduleCSV,
    io_operators.ImportP6,
    io_operators.ImportP6XER,
    io_operators.ImportPP,
    io_operators.ImportMSP,
    io_operators.ExportMSP,
    io_operators.ExportP6,

    # from operator.py (the rest of them)
    operator.Copy3D,
    operator.Sync3D,
    operator.AddSummaryTask,
    operator.AddTask,
    operator.AddTaskBars,
    operator.ClearTaskBars,
    operator.AddTaskColumn,
    operator.AddTimePeriod,
    operator.AddWorkCalendar,
    operator.AddWorkPlan,
    operator.AddWorkSchedule,
    operator.AddWorkTime,
    operator.AssignLagTime,
    operator.AssignPredecessor,
    operator.AssignProcess,
    operator.AssignProduct,
    operator.AssignRecurrencePattern,
    operator.AssignSuccessor,
    operator.AssignWorkSchedule,
    operator.Bonsai_DatePicker,
    operator.CalculateScheduleVariance,
    operator.ClearScheduleVariance,
    operator.CalculateTaskDuration,
    operator.ClearPreviousAnimation,
    operator.ClearPreviousSnapshot,
    operator.ContractAllTasks,
    operator.ContractTask,
    operator.CopyTask,
    operator.CopyTaskAttribute,
    operator.CopyTaskCustomcolortypeGroup,
    operator.CopyWorkSchedule,
    operator.CreateBaseline,
    operator.ANIM_OT_group_stack_add,
    operator.ANIM_OT_group_stack_remove,
    operator.ANIM_OT_group_stack_move,
    operator.DisableEditingSequence,
    operator.DisableEditingTask,
    operator.DisableEditingTaskTime,
    operator.DisableEditingWorkCalendar,
    operator.DisableEditingWorkPlan,
    operator.DisableEditingWorkSchedule,
    operator.DisableEditingWorkTime,
    operator.EditSequenceAttributes,
    operator.EditSequenceTimeLag,
    operator.EditTask,
    operator.EditTaskCalendar,
    operator.EditTaskTime,
    operator.EditWorkCalendar,
    operator.EditWorkPlan,
    operator.EditWorkSchedule,
    operator.EditWorkTime,
    operator.EnableEditingSequenceAttributes,
    operator.EnableEditingSequenceTimeLag,
    operator.EnableEditingTask,
    operator.EnableEditingTaskCalendar,
    operator.EnableEditingTaskSequence,
    operator.EnableEditingTaskTime,
    operator.EnableEditingWorkCalendar,
    operator.EnableEditingWorkCalendarTimes,
    operator.EnableEditingWorkPlan,
    operator.EnableEditingWorkPlanSchedules,
    operator.EnableEditingWorkSchedule,
    operator.EnableEditingWorkScheduleTasks,
    operator.EnableEditingWorkTime,
    operator.ExpandAllTasks,
    operator.ExpandTask,
    operator.GenerateGanttChart,
    operator.GuessDateRange,
    operator.GoToTask,
    operator.SortWorkScheduleByIdAsc,
    operator.LoadAnimationColorScheme,
    operator.LoadDefaultAnimationColors,
    operator.LoadProductTasks,
    operator.LoadTaskProperties,
    operator.RecalculateSchedule,
    operator.RefreshTaskOutputCounts,
    operator.RemoveTask,
    operator.RemoveTaskCalendar,
    operator.RemoveTaskColumn,
    operator.RemoveTimePeriod,
    operator.RemoveWorkCalendar,
    operator.RemoveWorkPlan,
    operator.RemoveWorkSchedule,
    operator.RemoveWorkTime,
    operator.ReorderTask,
    operator.SaveAnimationColorScheme,
    operator.SaveAnimationColorSchemesSetInternal,
    operator.LoadAnimationColorSchemesSetInternal,
    operator.RemoveAnimationColorSchemesSetInternal,
    operator.SelectTaskRelatedInputs,
    operator.SelectTaskRelatedProducts,
    operator.SelectUnassignedWorkScheduleProducts,
    operator.SelectWorkScheduleProducts,
    operator.SetTaskSortColumn,
    operator.SetupDefaultTaskColumns,
    operator.UnassignLagTime,
    operator.UnassignPredecessor,
    operator.UnassignProcess,
    operator.UnassignProduct,
    operator.UnassignRecurrencePattern,
    operator.UnassignSuccessor,
    operator.UnassignWorkSchedule,
    operator.SnapshotWithcolortypes,
    operator.AddSnapshotCamera,
    operator.AlignSnapshotCameraToView,
    operator.SnapshotWithcolortypesFixed,
    operator.VisualiseWorkScheduleDateRange,
    operator.DebugViewportInfo,
    operator.EnableStatusFilters,
    operator.DisableStatusFilters,
    operator.ActivateStatusFilters,
    operator.SelectStatusFilter,
    operator.UpdateActivecolortypeGroup,
    operator.InitializeColorTypeSystem,
    operator.BIM_OT_cleanup_colortype_groups,
    operator.BIM_OT_init_default_all_tasks,
    operator.VerifyCustomGroupsExclusion,
    operator.ShowcolortypeUIState,
    operator.AddAnimationColorSchemes,
    operator.RemoveAnimationColorSchemes,
    operator.ExportAnimationColorSchemesSetToFile,
    operator.ImportAnimationColorSchemesSetFromFile,
    operator.CleanupTaskcolortypeMappings,
    operator.SetupTextHUD,
    operator.ClearTextHUD,
    operator.UpdateTextHUDPositions,
    operator.UpdateTextHUDScale,
    operator.ToggleTextHUD,
    operator.Fix3DTextAlignment,
    operator.ArrangeScheduleTexts,
    operator.EnableScheduleHUD,
    operator.DisableScheduleHUD,
    operator.ToggleScheduleHUD,
    operator.RefreshScheduleHUD,
    operator.DebugScheduleHUD,
    operator.LegendHudcolortypeScrollUp,
    operator.LegendHudcolortypeScrollDown,
    operator.LegendHudTogglecolortypeVisibility,
    operator.Setup3DLegendHUD,
    operator.Clear3DLegendHUD,
    operator.Update3DLegendHUD,
    operator.Toggle3DLegendHUD,
    operator.DeactivateVarianceColorMode,
    operator.AddTaskFilter,
    operator.RemoveTaskFilter,
    operator.ApplyTaskFilters,
    operator.ClearAllTaskFilters,
    operator.ApplyLookaheadFilter,
    operator.FilterDatePicker,
    operator.SaveFilterSet,
    operator.LoadFilterSet,
    operator.RemoveFilterSet,
    operator.UpdateSavedFilterSet,
    operator.ExportFilterSet,
    operator.ImportFilterSet,
)

def register():
    """Registers all operator classes."""
    for cls in classes:
        bpy.utils.register_class(cls)

def unregister():
    """Unregisters all operator classes in reverse order."""
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)